### ISSUE TITLE
CEP Typescript Angular Configuration

### ISSUE THREAD

**Issue by radiumrasheed** [SturmB/sky-open-template#3]
Hello @SturmB 

I have seen so many of your discussions on CEP, Typescript and so on.
Do you have an update or answer on how to go about this?

I'm trying to migrate an electron-angular app written in TS to a panel app

**Comment by SturmB** [comment]
Hey, @radiumrasheed.

I replied to your post [on Adobe's Forums](https://community.adobe.com/t5/labs/adobe-cep-and-modern-frameworks/m-p/11287842?page=1#M9622). Check that out and let me know if that helps.
